### ISSUE TITLE
Error when i want to convert  png to img.

### ISSUE THREAD

**Issue by Alansanchez412** [Nenkai/Gran-Turismo-5-6-Modding-Guides#1]
I downloaded this pic 

https://static.wikia.nocookie.net/gran-turismo/images/a/a1/Clio_Renault_Sport_Trophy_V6_24V_Race_Car_%2700.jpg/revision/latest?cb=20181104202642

Which is used to add a image in my Clio Trophy created event but when i want to convert it into IMG it appears error. 

https://imgur.com/a/Hgve7B7

I tried with all formats and nothing. Also i noticed that TextConv is only compatible with 64-bit computers and i'm using only a 32-bit computers.  ¿Any way to convert any picture to  .IMG that works well? ¿Or maybe any alternative that works also in 32-bit computers?

I tried with this https://mygeodata.cloud/converter/png-to-img and when i paste to the specific folder which is event_flyer inside the piece folder and still nothing.

**Comment by Nenkai** [comment]
1. It's `--DXT5`, not `DXT5`.
2. Gran Turismo uses a custom format. Just using some converter online won't do. You must use this tool.
3. Nothing I can do about TexConv not supporting 32 bit systems. And to be honest, 32 bit processors have stopped being produced over a decade ago.

**Comment by Alansanchez412** [comment]
Yeah i did this and nothing this is the real error i encounter.

https://imgur.com/a/OjumAGO
